version: '3.1'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    ports:
      - 27018:8000

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    environment: 
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true 
    ports:
      - 9000:9000
